name: GitHub Profile Snake

on:
  schedule:
    - cron: '0 0 * * *'   # daily at midnight
  workflow_dispatch:

jobs:
  build-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Generate snake SVG
        run: |
          python3 <<EOF
          import requests
          from pathlib import Path
          # URL of a working snake generator API
          url = "https://raw.githubusercontent.com/Ileriayo/commit-snake/main/snake.py"
          code = requests.get(url).text
          with open("snake.py", "w") as f: f.write(code)
          exec(open("snake.py").read())
          EOF

      - name: Commit & Push
        run: |
          git config --global user.name "TiwariDivya25"
          git config --global user.email "divyat.social@gmail.com"
          git add snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
